[package]
name = "example_grpc_proto"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true


[lib]
name = "hello_proto"
path = "lib.rs"


[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
protoc-gen-prost = { workspace = true }
protoc-gen-tonic = { workspace = true }
