[package]
name = "build_pal_cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
build_pal_core = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
git2 = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
