[package]
name = "build_pal_server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
axum = { workspace = true }
build_pal_core = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
bollard = { workspace = true }
tokio-tungstenite = { workspace = true }
git2 = { workspace = true }
flate2 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
